### ISSUE TITLE
User agent string inconsistent

### ISSUE THREAD

**Issue by rferreira** [uvasoftware/scanii-lambda#7]
latest version is scanii-lambda-v0.4.0 and it should be something like scanii-lambda/v0.3.1

**Comment by lmatiolis** [comment]
Hi @rferreira! First of all, thanks for writing this code, it's really helping me to try out scanii on S3.

We are planning to use this lambda function and we were thinking about the version you are mentioning here. What is it used for? Just tracking the changes? And why do you think it needs to be with the `/` instead of `-`? Just better formatting?

Again, thanks for all the work here!

**Comment by rferreira** [comment]
Hey yeah this is purely cosmetic but we should make the user agent match the other client implementations that follow the pattern name + "/v" + semver

**Comment by lmatiolis** [comment]
@rferreira Ah, got it! That makes sense. Thanks for replying!

Should we create a PR for this? I noticed there's one open without activity for 1 year, so I was unsure about the state...

Thanks again!

**Comment by rferreira** [comment]
PRs are always welcomed! The inactivity is due to our focus on #8 (looking for ways to simplify the setup process).

**Comment by rferreira** [comment]
Fixed by https://github.com/uvasoftware/scanii-lambda/pull/11
